### ISSUE TITLE
How to deploy on Raspberry Pi 4 ?

### ISSUE THREAD

**Issue by akshara01** [bubblebeam/Inferno-Realtime-Fire-detection-using-CNNs#2]
Can you please guide on how did you use this model on Rpi ?

**Comment by bubblebeam** [comment]
@akshara01  sorry for the late reply. but the python code file threadcv.py is run on the raspberry pi. You can connect the raspberry pi to a monitor, and use it like a regular computer. You just need to copy threadcv.py and the trained model it uses to the rasp pi. You will also need to add a camera to the raspberry pi, so that it can get the frames.

please go through the research paper for more details: https://www.researchgate.net/publication/336639483_FPGA_Deployable_Fire_Detection_Model_for_Real-Time_Video_Surveillance_Systems_Using_Convolutional_Neural_Networks
